"""
================================================================================
Node Name   : TA LLM Prompt Selector
Created     : 2025
Modified    : 2026-03-11
Copyright   : © 2026, Thomas Möhrling (thomo.ART)
Version     : 2.0
--------------------------------------------------------------------------------
Part of ComfyUI-TA-Nodes-Pack
License     : Apache 2.0

Description:
    Selects between a text-to-image prompt and an image-to-image prompt based
    on the current LLM status. When the LLM is active and a text2prompt string
    is present, text2prompt is forwarded; otherwise image2prompt is used.
================================================================================
"""

import comfy


class TA_LLM_PromptSelector:
    """
    Automatically selects the appropriate prompt string based on LLM status.

    Routes to text2prompt when the LLM backend is active (llm_status is not
    'DISABLED') and text2prompt contains a non-empty string. Falls back to
    image2prompt in all other cases (LLM disabled, or no text prompt provided).
    """

    @classmethod
    def INPUT_TYPES(cls):
        """
        Defines all input widgets shown in the ComfyUI node UI.

        Inputs:
            llm_status:   Status string from an upstream LLM node. The value
                          'DISABLED' (or an empty string) indicates the LLM is
                          inactive; any other non-empty value is treated as active.
            text2prompt:  Prompt string generated by the LLM (text-to-image path).
            image2prompt: Fallback prompt string used when the LLM is inactive or
                          text2prompt is empty (image-to-image path).

        Returns:
            dict: ComfyUI INPUT_TYPES dictionary with all required inputs.
        """
        return {
            "required": {
                "llm_status": ("STRING", {
                    "default": "DISABLED",
                    "multiline": False
                }),
                "text2prompt": ("STRING", {
                    "multiline": True,
                    "default": ""
                }),
                "image2prompt": ("STRING", {
                    "multiline": True,
                    "default": ""
                })
            }
        }

    RETURN_TYPES = ("STRING",)
    FUNCTION = "select_prompt"
    CATEGORY = "ThomasAI"

    def select_prompt(self, llm_status, text2prompt, image2prompt):
        """
        Returns the appropriate prompt string based on LLM status and input content.

        Selection logic:
          - If llm_status is a non-empty string other than 'DISABLED' AND
            text2prompt is non-empty → return text2prompt.
          - Otherwise → return image2prompt.

        Args:
            llm_status (str):   Status indicator from an upstream LLM node.
                                'DISABLED' or empty string means the LLM is off.
            text2prompt (str):  LLM-generated prompt for the text-to-image path.
            image2prompt (str): Fallback prompt for the image-to-image path.

        Returns:
            tuple[str]: Single-element tuple containing the selected prompt string.
        """
        # Auto-select logic: use text2prompt if LLM is active and prompt is present,
        # otherwise fall back to image2prompt.
        if llm_status and llm_status.strip() != "DISABLED" and text2prompt.strip():
            return (text2prompt,)
        return (image2prompt,)
